### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Hyundai0** [qellzXan/dynamic_mem_finder#1]
uintptr_t simple_move_state_p2 = 0x34EAC68;
        uintptr_t simple_move_state_p1 = 0x34E75F8;
        uintptr_t throw_p1_address = 0x34E7620;   
        uintptr_t throw_p2_address = 0x34EAC90;
        uintptr_t adress_distance = 0x34DD480;
        uintptr_t attackType = 0x34EAB68;
        uintptr_t attackType_P1 = 0x34E74F8;
        uintptr_t adress_distance_second = 0x34E8620;
        
        how to find this addresses? please help me i found module base address and thats all

**Comment by Hyundai0** [comment]
Im trying to find adress with tekkenbotprime cheatengine project file

**Comment by qellzXan** [comment]
> ```
>    uintptr_t simple_move_state_p2 = 0x34EAC68;
>     uintptr_t simple_move_state_p1 = 0x34E75F8;
>     uintptr_t throw_p1_address = 0x34E7620;   
>     uintptr_t throw_p2_address = 0x34EAC90;
>     uintptr_t adress_distance = 0x34DD480;
>     uintptr_t attackType = 0x34EAB68;
>     uintptr_t attackType_P1 = 0x34E74F8;
>     uintptr_t adress_distance_second = 0x34E8620;
>     
>     how to find this addresses? please help me i found module base address and thats all
> ```
These are offsets.

to find them, I use the cheat engine. I find the value, and then the address and offsets to it.
